"""
Author: Zhengyuan Dong
Created: 2025-04-10
Last Modified: 2025-04-10
Description: This script is used to draw the system metrics curve from the JSON file generated by the starmie_metrics.py script.
Usage: 
    python -m src.data_analysis.starmie_metrics_topk --input ~/Repo/tmp/250409_starmie_debug/metrics_output.json --output metrics_plot.pdf
"""

import json
import argparse
import matplotlib.pyplot as plt

def load_metrics(filepath):
    """Load system_metrics from a JSON file."""
    with open(filepath, "r") as f:
        data = json.load(f)
    return data["system_metrics"]

def plot_metrics(metrics, output_path="metrics_plot.png"):
    """Plot precision, recall, MAP, and F1 curves and save the figure."""
    ks = metrics["used_k"]
    precision = metrics["precision"]
    recall = metrics["recall"]
    map_scores = metrics["map"]
    f1 = metrics["f1"]
    # print length
    print("Length of ks:", len(ks))
    ks = [int(k)+1 for k in range(len(precision))]
    print("Length of precision:", len(precision))
    print("Length of recall:", len(recall))
    print("Length of map_scores:", len(map_scores))
    print("Length of f1:", len(f1))

    #palette_resource = ["#486f90", "#4e8094", "#50a89d", "#a5d2bc"]
    palette_resource = ["#8b2e2e", "#d96e44", "#f29e4c", "#FFBE5F"] # , , "#b74a3c", 

    plt.figure(figsize=(10, 6))
    plt.plot(ks, precision, marker='o', label="Precision", color=palette_resource[0])
    plt.plot(ks, recall, marker='s', label="Recall", color=palette_resource[1])
    plt.plot(ks, map_scores, marker='^', label="MAP", color=palette_resource[2])
    plt.plot(ks, f1, marker='d', label="F1 Score", color=palette_resource[3])

    plt.xlabel("K")
    plt.ylabel("Score")
    plt.title("System Metrics vs K")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.savefig(output_path, dpi=300)
    plt.show()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Draw system metrics curve from JSON file.")
    parser.add_argument("--input", type=str, required=True, help="Path to metrics_output.json")
    parser.add_argument("--output", type=str, default="metrics_plot.png", help="Path to save the plot")
    args = parser.parse_args()

    print("Loading metrics from:", args.input)
    metrics = load_metrics(args.input)
    print("Loaded metrics!")
    print("Plotting metrics...")
    plot_metrics(metrics, output_path=args.output)
    print("Metrics plot saved to:", args.output)